### ISSUE TITLE
Possible missing column in popscle demuxlet output

### ISSUE THREAD

**Issue by asenabouth** [statgen/popscle#10]
Hello,
I was inspecting the output from demuxlet2 and have noticed the last column - DIFF.LLK.SNG.DBL is empty. This is probably due to SNG.BEST.LLK being text, rather than having a value. Also, the SNG.POSTERIOR and SNG.ONLY.POSTERIOR columns do not have numeric values; rather they have what appears to be their guess. Also, demuxlet 1 had the doublet posterior probability in the outputs; is still present in demuxlet 2's outputs?

| BARCODE            | NUM.SNPS | NUM.READS | DROPLET.TYPE | BEST.GUESS                                                                                                                             | BEST.LLK | NEXT.GUESS                                                                                                                             | NEXT.LLK | DIFF.LLK.BEST.NEXT | BEST.POSTERIOR | SNG.POSTERIOR                                                       | SNG.BEST.GUESS | SNG.BEST.LLK                                                       | SNG.NEXT.GUESS | SNG.NEXT.LLK | SNG.ONLY.POSTERIOR                                                                                                                     | DBL.BEST.GUESS | DBL.BEST.LLK | DIFF.LLK.SNG.DBL |
|--------------------|----------|-----------|--------------|----------------------------------------------------------------------------------------------------------------------------------------|----------|----------------------------------------------------------------------------------------------------------------------------------------|----------|--------------------|----------------|---------------------------------------------------------------------|----------------|--------------------------------------------------------------------|----------------|--------------|----------------------------------------------------------------------------------------------------------------------------------------|----------------|--------------|------------------|
| AAACCTGAGAGACGAA-1 | 96       | 101       | DBL          | TOB-00421_5504844381915111120733_UKB_G05-HUN6364A76_TOB-00421_F.CEL,WAB-00069_5504844381915111120733_UKB_H12-HUN6364A95_WAB-00069F.CEL | -45.73   | WAB-00069_5504844381915111120733_UKB_H12-HUN6364A95_WAB-00069F.CEL,TOB-00421_5504844381915111120733_UKB_G05-HUN6364A76_TOB-00421_F.CEL | -45.73   | 7.1e-15            | 6.9e-22        | TOB-00421_5504844381915111120733_UKB_G05-HUN6364A76_TOB-00421_F.CEL | 1.00           | WAB-00069_5504844381915111120733_UKB_H12-HUN6364A95_WAB-00069F.CEL | -49.00         | -75.75723    | TOB-00421_5504844381915111120733_UKB_G05-HUN6364A76_TOB-00421_F.CEL,WAB-00069_5504844381915111120733_UKB_H12-HUN6364A95_WAB-00069F.CEL | 0.00           | -45.73       |                  |
| AAACCTGAGAGTAAGG-1 | 1452     | 1671      | DBL          | WAB-00450_5504844381915111120732_UKB_C01_HUN6363A24_WAB-00450_F.CEL,FSA-00002_5504844385499012621171_UKB_A02_HUN6362A2_FSA-00002_F.CEL | -598.61  | FSA-00002_5504844385499012621171_UKB_A02_HUN6362A2_FSA-00002_F.CEL,WAB-00450_5504844381915111120732_UKB_C01_HUN6363A24_WAB-00450_F.CEL | -598.61  | 1.1e-13            | 5.3e-262       | WAB-00450_5504844381915111120732_UKB_C01_HUN6363A24_WAB-00450_F.CEL | 1.00           | FSA-00002_5504844385499012621171_UKB_A02_HUN6362A2_FSA-00002_F.CEL | -676.21        | -1038.21265  | WAB-00450_5504844381915111120732_UKB_C01_HUN6363A24_WAB-00450_F.CEL,FSA-00002_5504844385499012621171_UKB_A02_HUN6362A2_FSA-00002_F.CEL | 0.00           | -598.61      |                  |

This was the command that generated this data:
```bash
# Running popscle
popscle dsc-pileup --sam $INPUT_BAM --vcf $REF_VCF --out $PILEUP --group-list ${INPUT_BARCODES}

popscle demuxlet --plp $PILEUP --tag-group CB --tag-UMI UB \
--vcf $INPUT_VCF --sm-list $INPUT_SAMPLES --field GT \
--alpha 0 --alpha 0.5 --group-list $INPUT_BARCODES --out $DEMUXLET
```

Thanks,
Anne

**Comment by Griffan** [comment]
Yes, you are right. This bug has been fixed now.
