### ISSUE TITLE
Best Posterior Probability

### ISSUE THREAD

**Issue by drneavin** [statgen/popscle#11]
Hello,

I have been working with Freemuxlet in order to assign cells to individuals in multiplexed experiments. While investigating the output, I noticed that the BEST.POSTERIOR includes negative values. Can you help me understand how the posterior probability might have negative values in this situation? I have attached a figure that shows the range of values for one of my pools of multiplexed samples with the BEST.POSTERIOR on the x-axis
![Rplot02](https://user-images.githubusercontent.com/44268007/59824497-a37edb00-9374-11e9-85a1-0496760e9caa.jpeg)

Thanks for your help!

**Comment by hyunminkang** [comment]
This might be related to the recently reported and fixed bug in column
names. Does the newer version still cause the problem?

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by asenabouth** [comment]
Hello,
I'm not sure if freemuxlet uses the same code as demuxlet for these functions, but I patched my version of popscle and ran the sample again. My best posterior probability values are negative, and all the values in SNG.POSTERIOR are 1 and SNG.ONLY.POSTERIOR are 0. The output does identify singlets and doublets however. I ran the same data in demuxlet 1 and got a range of values.

**Comment by drneavin** [comment]
I am also still getting negative posterior probabilities with the fixed bug for Freemuxlet.

**Comment by Griffan** [comment]
The bug should be fixed now, please update the repo and try again. 

The reason for the negative PP is that we failed to correct all the log-scale transformations in the last commit, because of slightly different variable naming style between demuxlet and freemuxlet.

As for the bug that "SNG.POSTERIOR being 1", it's due to wrong initialization.

Thanks for your feedback!

**Comment by asenabouth** [comment]
Yep, it now looks good. Thanks!
