### ISSUE TITLE
installing error!!!

### ISSUE THREAD

**Issue by hi9739** [statgen/popscle#14]
Hi, I'm having some trouble popscle installing in Ubuntu
I really want to demultiplexing my single cell RNA data with popscle!!
I don't know what is the problem
Thank you very much
Best Regards,
sukjung

Ubuntu18.04
install htslib in sibling directory
gcc 7.4
cmake 3.10.2
-------------------------------------------------------------------------------------------------------
description in each step
-------------------------------------------------------------------------------------------------------
1.cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /usr/local/include
-- /usr/local/lib/libhts.so
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sjchoi/Shared/ssRNA/popscle-master/build
2. make
Scanning dependencies of target popscle
[ 2%] Building CXX object CMakeFiles/popscle.dir/allele.cpp.o
[ 5%] Building CXX object CMakeFiles/popscle.dir/bam_ordered_reader.cpp.o
[ 8%] Building CXX object CMakeFiles/popscle.dir/bcf_chunked_reader.cpp.o
[ 11%] Building CXX object CMakeFiles/popscle.dir/bcf_filtered_reader.cpp.o
/home/sjchoi/Shared/ssRNA/popscle-master/bcf_filtered_reader.cpp: In member function ‘std::__cxx11::string& BCFFilteredReader::get_var_ID(bcf_hdr_t*, bcf1_t*)’:
/home/sjchoi/Shared/ssRNA/popscle-master/bcf_filtered_reader.cpp:496:26: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘hts_pos_t {aka long int}’ [-Wformat=]
sprintf(buf,"%d",v->pos);
~~~~~~^
[ 14%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_demuxlet.cpp.o
[ 17%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_digital_pileup.cpp.o
[ 20%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_freemuxlet.cpp.o
[ 23%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_freemux2.cpp.o
[ 26%] Building CXX object CMakeFiles/popscle.dir/cmd_plp_make_dge_matrix.cpp.o
[ 29%] Building CXX object CMakeFiles/popscle.dir/commands.cpp.o
[ 32%] Building CXX object CMakeFiles/popscle.dir/cramore.cpp.o
[ 35%] Building CXX object CMakeFiles/popscle.dir/dropseq.cpp.o
[ 38%] Building CXX object CMakeFiles/popscle.dir/Error.cpp.o
[ 41%] Building CXX object CMakeFiles/popscle.dir/filter.cpp.o
[ 44%] Building CXX object CMakeFiles/popscle.dir/genome_interval.cpp.o
[ 47%] Building CXX object CMakeFiles/popscle.dir/genomeChunk.cpp.o
[ 50%] Building CXX object CMakeFiles/popscle.dir/gtf.cpp.o
[ 52%] Building CXX object CMakeFiles/popscle.dir/hts_utils.cpp.o
[ 55%] Building CXX object CMakeFiles/popscle.dir/interval.cpp.o
[ 58%] Building CXX object CMakeFiles/popscle.dir/interval_tree.cpp.o
[ 61%] Building CXX object CMakeFiles/popscle.dir/IO.cpp.o
[ 64%] Building CXX object CMakeFiles/popscle.dir/log_tool.cpp.o
[ 67%] Building CXX object CMakeFiles/popscle.dir/params.cpp.o
[ 70%] Building CXX object CMakeFiles/popscle.dir/PhredHelper.cpp.o
[ 73%] Building CXX object CMakeFiles/popscle.dir/reference_sequence.cpp.o
[ 76%] Building CXX object CMakeFiles/popscle.dir/sam_filtered_reader.cpp.o
[ 79%] Building CXX object CMakeFiles/popscle.dir/sam_ordered_writer.cpp.o
/home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp: In member function ‘void SAMOrderedWriter::write(bam1_t*)’:
/home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:138:90: error: no matching function for call to ‘max(hts_pos_t, int)’
int32_t cutoff_pos1 = std::max(bam_get_pos1(buffer.front())-window,1);
^
In file included from /usr/include/c++/7/vector:60:0,
from /home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.h:32,
from /home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:24:
/usr/include/c++/7/bits/stl_algobase.h:219:5: note: candidate: template constexpr const _Tp& std::max(const _Tp&, const _Tp&)
max(const _Tp& __a, const _Tp& __b)
^~~
/usr/include/c++/7/bits/stl_algobase.h:219:5: note: template argument deduction/substitution failed:
/home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:138:90: note: deduced conflicting types for parameter ‘const _Tp’ (‘long int’ and ‘int’)
int32_t cutoff_pos1 = std::max(bam_get_pos1(buffer.front())-window,1);
^
In file included from /usr/include/c++/7/vector:60:0,
from /home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.h:32,
from /home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:24:
/usr/include/c++/7/bits/stl_algobase.h:265:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^~~
/usr/include/c++/7/bits/stl_algobase.h:265:5: note: template argument deduction/substitution failed:
/home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:138:90: note: deduced conflicting types for parameter ‘const _Tp’ (‘long int’ and ‘int’)
int32_t cutoff_pos1 = std::max(bam_get_pos1(buffer.front())-window,1);
^
/home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp: In member function ‘void SAMOrderedWriter::flush(bool)’:
/home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:221:76: error: no matching function for call to ‘max(hts_pos_t, int)’
int32_t cutoff_pos1 = std::max(bam_get_pos1(buffer.front())-window,1);
^
In file included from /usr/include/c++/7/vector:60:0,
from /home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.h:32,
from /home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:24:
/usr/include/c++/7/bits/stl_algobase.h:219:5: note: candidate: template constexpr const _Tp& std::max(const _Tp&, const _Tp&)
max(const _Tp& __a, const _Tp& __b)
^~~
/usr/include/c++/7/bits/stl_algobase.h:219:5: note: template argument deduction/substitution failed:
/home/sjchoi/Shared/ssRNA/popscle-master/sam_ordered_writer.cpp:221:76: note: deduced conflicting types for parameter ‘const _Tp’ (‘long int’ and ‘int’)
int32_t cutoff_pos1 = std::max(bam_get_pos1(buffer.front())-window,1);
^

**Comment by Griffan** [comment]
This error is introduced by a recent htslib update 14 days ago: 

https://github.com/samtools/htslib/blob/7fc833d07462ff59dfbad30e8f517f4301eed433/README.large_positions.md

I will try to update our code accordingly, however, a quick workaround for you is to downgrade your htslib to a older version.

**Comment by Griffan** [comment]
I have pushed a patch to fix this issue. You can update your popscle repo to complie now.
