### ISSUE TITLE
dsc-pileup doesn't recognize AF tags in VCF from Mutect2

### ISSUE THREAD

**Issue by yh154** [statgen/popscle#15]
Hi
I am trying to use dsc-pileup with a VCF generated by GATK3 Mutect2 and it seems that dsc-pileup can't parsing this VCF file properly. Highly appreciated if you could provide some insight on it. Thanks! 

**The command I used:** 
bin/popscle dsc-pileup --sam mapped.sorted.bam --vcf mutect2_output_sorted.vcf.gz --out result/dsc_pileup.out_ 

**Messages I got up to error:** 
NOTICE [2019/10/16 16:43:11] - Initializing BCF reader..
NOTICE [2019/10/16 16:43:11] - Finished identifying 1 samples to load from VCF/BCF
NOTICE [2019/10/16 16:43:11] - Initializing SAM reader..
NOTICE [2019/10/16 16:43:11] - WARNING: Cannot find AF field from INFO field in VCF file, now calculate AF from AC/AN
Segmentation fault: 11

**One line of the VCF file looks like:** 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	tumor_sample
1	186365	.	T	C	.	PASS	ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;TLOD=12.56	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/1:7,6:0.462:0:0:.:213,136:0:0

**Comment by Griffan** [comment]
popscle expects AF(allele frequency) to be in the INFO field, which usually can be obtained from common database like 1000g or dbsnp.
