### ISSUE TITLE
popscle provided Dockerfile fails to build

### ISSUE THREAD

**Issue by joshua-gould** [statgen/popscle#18]
/popscle/sam_ordered_writer.cpp: In member function 'void SAMOrderedWriter::write(bam1_t*)':
/popscle/sam_ordered_writer.cpp:138:92: error: no matching function for call to 'max(hts_pos_t, long long int)'
                     int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,1LL);
                                                                                            ^
In file included from /usr/include/c++/7/vector:60:0,
                 from /popscle/sam_ordered_writer.h:32,
                 from /popscle/sam_ordered_writer.cpp:24:
/usr/include/c++/7/bits/stl_algobase.h:219:5: note: candidate: template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:219:5: note:   template argument deduction/substitution failed:
/popscle/sam_ordered_writer.cpp:138:92: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'long long int')
                     int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,1LL);
                                                                                            ^
In file included from /usr/include/c++/7/vector:60:0,
                 from /popscle/sam_ordered_writer.h:32,
                 from /popscle/sam_ordered_writer.cpp:24:
/usr/include/c++/7/bits/stl_algobase.h:265:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
/popscle/sam_ordered_writer.cpp:138:92: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'long long int')
                     int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,1LL);
                                                                                            ^
/popscle/sam_ordered_writer.cpp: In member function 'void SAMOrderedWriter::flush(bool)':
/popscle/sam_ordered_writer.cpp:221:78: error: no matching function for call to 'max(hts_pos_t, long long int)'
       int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,1LL);
                                                                              ^
In file included from /usr/include/c++/7/vector:60:0,
                 from /popscle/sam_ordered_writer.h:32,
                 from /popscle/sam_ordered_writer.cpp:24:
/usr/include/c++/7/bits/stl_algobase.h:219:5: note: candidate: template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:219:5: note:   template argument deduction/substitution failed:
/popscle/sam_ordered_writer.cpp:221:78: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'long long int')
       int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,1LL);
                                                                              ^
In file included from /usr/include/c++/7/vector:60:0,
                 from /popscle/sam_ordered_writer.h:32,
                 from /popscle/sam_ordered_writer.cpp:24:
/usr/include/c++/7/bits/stl_algobase.h:265:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
/popscle/sam_ordered_writer.cpp:221:78: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'long long int')
       int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,1LL);
                                                                              ^
make[2]: *** [CMakeFiles/popscle.dir/sam_ordered_writer.cpp.o] Error 1

**Comment by Griffan** [comment]
This problem is also related to hts_pos_t in htslib. It's been fixed in the latest commit, please let me know if it works on your end.

**Comment by joshua-gould** [comment]
It works, thanks.
