### ISSUE TITLE
popscle :: error that throw pexception => core dump

### ISSUE THREAD

**Issue by EricDeveaud** [statgen/popscle#19]
hello, 

while running some testing before installing popscle on our cluster I found that whne  an error message raised, it ends with 
```
throw pexception
```

on our environement this will ends with 
```
terminate called after throwing an instance of 'pException'
  what():  Exception was thrown
zsh: abort (core dumped) popscle xyz .....
```

is there a reason you choose this instead of the commented exit(EXIT_FAILURE); in Errors.cpp
debug I assume 
for production release exit failure will be more suitable.

regards

Eric

**Comment by Griffan** [comment]
Thanks for your suggestion, we will try to address these issues in the stable release.
