### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by xAZx** [statgen/popscle#21]
Hi All,

I am having installation errors while installing popscle. I looked through previous resolved issues and found slightly similar issues from others, but not quite the same as mine. I am using the `make` command at the last step per below:

`PowerEdge-T610:~/popscle/build$ make`

And then get this output and error!

**[  3%] Building CXX object CMakeFiles/popscle.dir/bam_ordered_reader.cpp.o
/home/sarwal/popscle/bam_ordered_reader.cpp: In member function ‘void BAMOrderedReader::close()’:
/home/sarwal/popscle/bam_ordered_reader.cpp:204:11: error: ‘nullptr’ was not declared in this scope
     hdr = nullptr;
           ^
make[2]: *** [CMakeFiles/popscle.dir/bam_ordered_reader.cpp.o] Error 1
make[1]: *** [CMakeFiles/popscle.dir/all] Error 2
make: *** [all] Error 2**

I am using htslib 1.8, and g++ 4.8.4. 

Many thanks in advance!

**Comment by Griffan** [comment]
It's likely a problem related to gcc version, you can try solutions mentioned in this link:https://stackoverflow.com/questions/10033373/c-error-nullptr-was-not-declared-in-this-scope-in-eclipse-ide

**Comment by hyunminkang** [comment]
We will fix this, but I believe that you can fix yourself by changing the
line in CMakeLists.txt from

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -pthread")

to

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -pthread --std=c++11")

I will appreciate if you provide us with feedback on whether the change
worked or not

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by xAZx** [comment]
Thank you for your response. I made the changes your recommended in the CMakeLists.txt file. After running `make`, it made much more progress, but unfortunately ran into a new error:

[  3%] Building CXX object CMakeFiles/popscle.dir/interval_tree.cpp.o
[  3%] Building CXX object CMakeFiles/popscle.dir/IO.cpp.o
[  3%] Building CXX object CMakeFiles/popscle.dir/log_tool.cpp.o
[  3%] Building CXX object CMakeFiles/popscle.dir/params.cpp.o
[  3%] Building CXX object CMakeFiles/popscle.dir/PhredHelper.cpp.o
[  3%] Building CXX object CMakeFiles/popscle.dir/reference_sequence.cpp.o
[  3%] Building CXX object CMakeFiles/popscle.dir/sam_filtered_reader.cpp.o
[  3%] Building CXX object CMakeFiles/popscle.dir/sam_ordered_writer.cpp.o
/home/sarwal/popscle/sam_ordered_writer.cpp: In member function ‘void SAMOrderedWriter::write(bam1_t*)’:
/home/sarwal/popscle/sam_ordered_writer.cpp:138:101: error: expected type-specifier before ‘hts_pos_t’
                     int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,static_cast<hts_pos_t>(1));
                                                                                                     ^
/home/sarwal/popscle/sam_ordered_writer.cpp:138:101: error: expected ‘>’ before ‘hts_pos_t’
/home/sarwal/popscle/sam_ordered_writer.cpp:138:101: error: expected ‘(’ before ‘hts_pos_t’
/home/sarwal/popscle/sam_ordered_writer.cpp:138:101: error: ‘hts_pos_t’ was not declared in this scope
/home/sarwal/popscle/sam_ordered_writer.cpp: In member function ‘void SAMOrderedWriter::flush(bool)’:
/home/sarwal/popscle/sam_ordered_writer.cpp:221:87: error: expected type-specifier before ‘hts_pos_t’
       int64_t cutoff_pos1 =  std::max(bam_get_pos1(buffer.front())-window,static_cast<hts_pos_t>(1));
                                                                                       ^
/home/sarwal/popscle/sam_ordered_writer.cpp:221:87: error: expected ‘>’ before ‘hts_pos_t’
/home/sarwal/popscle/sam_ordered_writer.cpp:221:87: error: expected ‘(’ before ‘hts_pos_t’
/home/sarwal/popscle/sam_ordered_writer.cpp:221:87: error: ‘hts_pos_t’ was not declared in this scope
make[2]: *** [CMakeFiles/popscle.dir/sam_ordered_writer.cpp.o] Error 1
make[1]: *** [CMakeFiles/popscle.dir/all] Error 2
make: *** [all] Error 2

Any thoughts? Thank you in advance.

**Comment by Griffan** [comment]
I think you can try to upgrade htslib to 1.10 to fix this issue.
From 1.10 onward, htslib introduced hts_pos_t to accommodate large genome coordinates.

**Comment by xAZx** [comment]
This did the trick! Thank you so much.
