### ISSUE TITLE
demuxlet version to use

### ISSUE THREAD

**Issue by drneavin** [statgen/popscle#24]
Popscle developers,

I recently compared the output of the published demuxlet and demuxlet run from popscle. While the majority of the assignments are the same, there are some differences between the assignments and the doublet and singlet log likelihoods even though the number of SNPs and reads used are highly consistent.

I've noticed that the main differences seem to stem from the geno_error which is now split into geno-error-offset and geno-error-rate and the r2-info option. Could you comment on the differences in the algorithms contributing to the differences in the cell assignment and which demuxlet version you suggest users to use at this time (beta popscle or demuxlet)?

Thanks!

**Comment by hyunminkang** [comment]
geno-error-offset  should be the same as geno-error parameters.

geno-error-rate assumes that genotype error is proportional to the
imputation quality, which is R2 in the INFO field, or something you can
specify using --r2-info.

We encourage to set geno-error-rate to nonzero when using imputed
genotypes, but if it is not imputed genotypes, geno-error-rate do not need
to be used, and the current default is 0.

Thanks,
Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by drneavin** [comment]
Thanks for the helpful response Hyun!

I have a couple of followup questions based on your response. First, do you have a recommended range for the geno-error-rate? I'm thinking that 0.1 might be a good option?

Also, while geno-error-offset is 0.1 by default, geno-error was 0.01 by default in the previous version of demuxlet. Any reason for this change? I would think that 0.01 is more reflective of genotype error rates.

Thanks again for your help!

Best,
Drew

**Comment by hyunminkang** [comment]
Yes 0.1 is better from my perspective. I did not realize 0.01 was default
in original demuxlet. 0.1 seems working better so I will change demuxlet v1
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by drneavin** [comment]
Sounds great Hyun, also what is your recommendation for the range for the geno-error-rate when using genotyped data?

**Comment by hyunminkang** [comment]
Set it to 0. No need to use it unless imputed.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by drneavin** [comment]
Hi Hyun,

We do indeed have imputes data so I would like to know the value or range of values that you would recommend for this parameter when using imputed data.

Thanks!
-Drew

**Comment by drneavin** [comment]
Hi Hyun,

Any update on the range of values to use for the geno-error-rate when using imputed data?

Cheers,
Drew

**Comment by hyunminkang** [comment]
We do not have specific recommendations as optimal parameter can vary and
this is a heuristic.
The parameter I tried was geno-error-coeff 1.0 geno-error-offset 0.05 (or
0.1) and it seems to be working fine.

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by drneavin** [comment]
Great, thanks Hyun! That is along the range that I was thinking might be appropriate and it is good to know that ~0.05 or 0.1 is a good starting range to use.

Cheers,
Drew
