### ISSUE TITLE
Reference files and chromosome ordering

### ISSUE THREAD

**Issue by Lopiniatre** [statgen/popscle#25]
Hi, 
I tried to used 1000 genome reference vcf directly download from their last release for dsc-pileup using
`popscle dsc-pileup --sam "$dataloc/possorted_genome_bam.bam" --vcf <(gzcat ~/genome/1000g/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz) --out pileupOUT --group-list <(gzcat "$dataloc/filtered_feature_bc_matrix/barcodes.tsv.gz")`
and got the following error:
```
NOTICE [2020/02/25 20:31:16] - Finished loading 7437 droplet/cell barcodes to consider
NOTICE [2020/02/25 20:31:16] - Initializing BCF reader..
NOTICE [2020/02/25 20:31:16] - Finished identifying 0 samples to load from VCF/BCF
NOTICE [2020/02/25 20:31:16] - Initializing SAM reader..
FATAL ERROR - 
[E:int32_t cmdCramDigitalPileup(int32_t, char**)] Your VCF/BCF files and SAM/BAM/CRAM files have different ordering of chromosomes. SAM/BAM/CRAM file has 19 before 2, but VCF/BCF file has 19 after 2
```
As my .bam is coming directly from 10X CellRanger, there seems to be an ordering contradiction. I also notice this 0 samples identified from vcf which suggest I'm not using the correct vcf

I'm relatively new at working with vcf and alignement tools like htslib/samtools or picard: 
Which reference file shoud I use from 1000 genome? (a link in the tutorial would help) 
What is the best way to make it compatible with 10X bam and make dsc-pileup work?
Thank you for any advice,
Best,

**Comment by Gvaihir** [comment]
Your vcf could be ok, just ordering in the header may be wrong.
2 alternative workarounds:
1) delete all lines with "contig" in the header or
2) recreate header with vcf- (or bcf-) tools

**Comment by Lopiniatre** [comment]
Thank you @Gvaihir ,
 I suppressed the ##contig lines from the vcf using
`zcat ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz | sed '/^##contig/d' | gzip -c > ref_stripped.vcf.gz`

Using this new vcf the process starts 
> Finished loading 7437 droplet/cell barcodes to consider
NOTICE [2020/02/26 11:40:33] - Initializing BCF reader..
NOTICE [2020/02/26 11:40:33] - Finished identifying 0 samples to load from VCF/BCF
NOTICE [2020/02/26 11:40:33] - Initializing SAM reader..
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)Reading 0 reads at 1:1 and skipping 0

with multiple of those warnings:

> NOTICE [2020/02/26 11:40:33] - WARNING: Cannot find Droplet/Cell tag UB from 4748-th read A00124:177:H3C7VDSXY:2:1113:27127:25895 at 1:14674-14765. Treating all of them as a single group
WARNING: Cannot find UMI tag UB from 508418-th read A00124:177:H3C7VDSXY:2:2207:31114:22623 at 1:632628-632703. Treating all of them as a single UMI

before proceeding

> NOTICE [2020/02/26 11:46:09] - Reading 10000 variants at 1:915492, Skipping 0, Missing 0.
NOTICE [2020/02/26 11:46:49] - Reading 20000 variants at 1:1159061, Skipping 0, Missing 0.
NOTICE [2020/02/26 11:53:00] - Reading 30000 variants at 1:1394506, Skipping 0, Missing 0.

Any idea what those Cell tag and UMI tag warning are coming from and impact the process?

**Comment by Gvaihir** [comment]
Some reads in your BAM miss UMI or CB. I sometimes have it - usually doesn't affect performance. 
If VCF order resolved please close the issue.
Thanks!

**Comment by ghuls** [comment]
@Lopiniatre I made a script to resort the VCF file according to the chromosome order in the BAM file. So in case you need it in the future take a look at:
https://github.com/aertslab/popscle_helper_tools#sort-vcf-file-in-the-same-order-as-the-bam-file
