### ISSUE TITLE
bh_tsne.cpp:149:35: error: call of overloaded ‘isinf(double&)’ is ambiguous.

### ISSUE THREAD

**Issue by guanyuanm** [statgen/popscle#3]
Hi Griffan,
When I did 'make' step, the error is below:
bh_tsne.cpp:149:35: error: call of overloaded ‘isinf(double&)’ is ambiguous.
thanks!

**Comment by Griffan** [comment]
Could you share with me your compiler version and OS platform and version?

**Comment by guanyuanm** [comment]
$gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/share/software/user/open/gcc/6.3.0/libexec/gcc/x86_64-pc-linux-gnu/6.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-6.3.0/configure --prefix=/share/software/user/open/gcc/6.3.0/ --enable-languages=c,c++,fortran,go,java --disable-multilib
Thread model: posix
gcc version 6.3.0 (GCC)

**Comment by Griffan** [comment]
Could you give a try again? It's due to namespace conflict, which should be fine now.

**Comment by guanyuanm** [comment]
Great, Thanks a lot! 
Actually, I did something else to make it (manually direct to GCC 6.3, which I have another old version in system)
