### ISSUE TITLE
wrong demo files in google cloud drive disk

### ISSUE THREAD

**Issue by vagabond12** [statgen/popscle#36]
https://drive.google.com/drive/folders/1wfnn132vMbZhicpWOZVbR_36YpIiojug?usp=sharing

The right file should be jurkat_293t_downsampled_n500_full_bam.bam file, but you supply us the bai file jurkat_293t_downsampled_n500_full_bam.bai.

We do not think this example would embody the function of the software. For you use the same VCF file.

I still do not know how to manage mixed samples without external genotyping data.

**Comment by hyunminkang** [comment]
Both .bam and .bai file is available in the driver.

**Comment by hyunminkang** [comment]
I replied too soon. Actually the BAM file is only accessible within University of Michigan due to oversight in the permission setting. We will try to change the setting and will let you know if this is done. Sorry for the confusion and thanks for the feedback.

**Comment by hyunminkang** [comment]
The file should be visible now. Let me know otherwise.

**Comment by vagabond12** [comment]
Thank you very much. I can download the file now, and the  tutorial  works well. 
     However, as many users inquired, I do not know how to get the VCF file for Homo sapiens or Macaca fascicularis from 1000 genomics. And we hope you could help us, uploading the VCF file to the cloud disk or giving us a download link would be greatly apprecidated. Thank you very much.
