### ISSUE TITLE
Error Linking CXX executable

### ISSUE THREAD

**Issue by jjenny** [statgen/popscle#38]
Hi,

I get the following error when I try to build popscle at the last step:

Linking CXX executable ../bin/popscle
/usr/bin/ld: header.o: access beyond end of merged section (2414)
/usr/bin/ld: header.o: access beyond end of merged section (4392)
/usr/bin/ld: header.o: access beyond end of merged section (2019)
/usr/bin/ld: header.o: access beyond end of merged section (4268)
/usr/bin/ld: header.o: access beyond end of merged section (2673)
/usr/bin/ld: header.o: access beyond end of merged section (3845)
/usr/bin/ld: header.o: access beyond end of merged section (3270)
/usr/bin/ld: header.o: access beyond end of merged section (3692)
/usr/bin/ld: header.o: access beyond end of merged section (2435)
/usr/bin/ld: header.o: access beyond end of merged section (3799)
/usr/bin/ld: header.o: access beyond end of merged section (3126)
/usr/bin/ld: header.o: access beyond end of merged section (4259)
/usr/bin/ld: header.o: access beyond end of merged section (2218)
/usr/bin/ld: header.o: access beyond end of merged section (3324)
/usr/bin/ld: header.o: access beyond end of merged section (3261)
/usr/bin/ld: header.o: access beyond end of merged section (2505)
/usr/bin/ld: header.o: access beyond end of merged section (3289)
/usr/bin/ld: header.o: access beyond end of merged section (2374)
/usr/bin/ld: header.o: access beyond end of merged section (3195)
/usr/bin/ld: header.o: access beyond end of merged section (2546)
/usr/bin/ld: header.o: access beyond end of merged section (2801)
/usr/bin/ld: header.o: access beyond end of merged section (3218)
/usr/bin/ld: header.o: access beyond end of merged section (2388)
/usr/bin/ld: header.o: access beyond end of merged section (4183)
/usr/bin/ld: header.o: access beyond end of merged section (3864)
/usr/bin/ld: header.o: access beyond end of merged section (2826)
/usr/bin/ld: header.o: access beyond end of merged section (4100)
/usr/bin/ld: header.o: access beyond end of merged section (2097)
/usr/bin/ld: header.o: access beyond end of merged section (4303)
/usr/bin/ld: header.o: access beyond end of merged section (2514)
/usr/bin/ld: header.o: access beyond end of merged section (2630)
/usr/bin/ld: header.o: access beyond end of merged section (3758)
/usr/bin/ld: header.o: access beyond end of merged section (3552)
/usr/bin/ld: header.o: access beyond end of merged section (4192)
/usr/bin/ld: header.o: access beyond end of merged section (2054)
/usr/bin/ld: header.o: access beyond end of merged section (2237)
/usr/bin/ld: header.o: access beyond end of merged section (3963)
/usr/bin/ld: header.o: access beyond end of merged section (3568)
/usr/bin/ld: header.o: access beyond end of merged section (2709)
/usr/bin/ld: header.o: access beyond end of merged section (2716)
/usr/bin/ld: header.o: access beyond end of merged section (2723)
/usr/bin/ld: header.o: access beyond end of merged section (2730)
/usr/bin/ld: header.o: access beyond end of merged section (2737)
/usr/bin/ld: header.o: access beyond end of merged section (2852)
/usr/bin/ld: header.o: access beyond end of merged section (2141)
/usr/bin/ld: header.o: access beyond end of merged section (3686)
/usr/bin/ld: header.o: access beyond end of merged section (2752)
/usr/bin/ld: header.o: access beyond end of merged section (3625)
/usr/bin/ld: header.o: access beyond end of merged section (4287)
/usr/bin/ld: header.o: access beyond end of merged section (3838)
/usr/bin/ld: header.o: access beyond end of merged section (3933)
/usr/bin/ld: header.o: access beyond end of merged section (3933)
/usr/bin/ld: header.o: access beyond end of merged section (3855)
/usr/bin/ld: header.o: access beyond end of merged section (4242)
/usr/bin/ld: header.o: access beyond end of merged section (2130)
/usr/bin/ld: header.o: access beyond end of merged section (4212)
/usr/bin/ld: header.o: access beyond end of merged section (2643)
/usr/bin/ld: header.o: access beyond end of merged section (2336)
/usr/bin/ld: header.o: access beyond end of merged section (2951)
/usr/bin/ld: header.o: access beyond end of merged section (3284)
/usr/bin/ld: header.o: access beyond end of merged section (3663)
/usr/bin/ld: header.o: access beyond end of merged section (2528)
/usr/bin/ld: header.o: access beyond end of merged section (4254)
/usr/bin/ld: header.o: access beyond end of merged section (3042)
/usr/bin/ld: header.o: access beyond end of merged section (2833)
/usr/bin/ld: header.o: access beyond end of merged section (2976)
/usr/bin/ld: header.o: access beyond end of merged section (2498)
/usr/bin/ld: header.o: access beyond end of merged section (4558)
/usr/bin/ld: header.o: access beyond end of merged section (4200)
/usr/bin/ld: header.o: access beyond end of merged section (2758)
/usr/bin/ld: header.o: access beyond end of merged section (3907)
/usr/bin/ld: header.o: access beyond end of merged section (2314)
/usr/bin/ld: header.o: access beyond end of merged section (2111)
/usr/bin/ld: header.o: access beyond end of merged section (2423)
/usr/bin/ld: header.o: access beyond end of merged section (3923)
/usr/bin/ld: header.o: access beyond end of merged section (2203)
/usr/bin/ld: header.o: access beyond end of merged section (3312)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (4062)
/usr/bin/ld: header.o: access beyond end of merged section (2062)
/usr/bin/ld: header.o: access beyond end of merged section (4382)
/usr/bin/ld: header.o: access beyond end of merged section (2618)
/usr/bin/ld: header.o: access beyond end of merged section (4361)
/usr/bin/ld: header.o: access beyond end of merged section (4361)
/usr/bin/ld: header.o: access beyond end of merged section (4586)
/usr/bin/ld: header.o: access beyond end of merged section (3993)
/usr/bin/ld: header.o: access beyond end of merged section (2276)
/usr/bin/ld: header.o: access beyond end of merged section (4504)
/usr/bin/ld: header.o: access beyond end of merged section (3359)
/usr/bin/ld: header.o: access beyond end of merged section (3166)
/usr/bin/ld: header.o: access beyond end of merged section (3978)
/usr/bin/ld: header.o: access beyond end of merged section (2744)
/usr/bin/ld: header.o: access beyond end of merged section (4607)
/usr/bin/ld: header.o: access beyond end of merged section (3711)
/usr/bin/ld: header.o: access beyond end of merged section (4459)
/usr/bin/ld: header.o: access beyond end of merged section (2473)
/usr/bin/ld: header.o: access beyond end of merged section (2176)
/usr/bin/ld: header.o: access beyond end of merged section (3923)
/usr/bin/ld: header.o: access beyond end of merged section (2865)
/usr/bin/ld: header.o: access beyond end of merged section (4542)
/usr/bin/ld: header.o: access beyond end of merged section (2880)
/usr/bin/ld: header.o: access beyond end of merged section (2577)
/usr/bin/ld: header.o: access beyond end of merged section (4542)
/usr/bin/ld: header.o: access beyond end of merged section (4581)
/usr/bin/ld: header.o: access beyond end of merged section (3487)
/usr/bin/ld: header.o: access beyond end of merged section (3540)
/usr/bin/ld: header.o: access beyond end of merged section (2593)
/usr/bin/ld: header.o: access beyond end of merged section (3785)
/usr/bin/ld: header.o: access beyond end of merged section (2686)
/usr/bin/ld: header.o: access beyond end of merged section (3785)
/usr/bin/ld: header.o: access beyond end of merged section (3785)
/usr/bin/ld: header.o: access beyond end of merged section (3232)
/usr/bin/ld: header.o: access beyond end of merged section (3425)
/usr/bin/ld: header.o: access beyond end of merged section (2772)
/usr/bin/ld: header.o: access beyond end of merged section (3154)
/usr/bin/ld: header.o: access beyond end of merged section (4002)
/usr/bin/ld: header.o: access beyond end of merged section (3721)
/usr/bin/ld: header.o: access beyond end of merged section (3181)
/usr/bin/ld: header.o: access beyond end of merged section (4123)
/usr/bin/ld: header.o: access beyond end of merged section (2369)
/usr/bin/ld: header.o: access beyond end of merged section (4019)
/usr/bin/ld: header.o: access beyond end of merged section (2075)
/usr/bin/ld: header.o: access beyond end of merged section (3721)
/usr/bin/ld: header.o: access beyond end of merged section (3181)
/usr/bin/ld: header.o: access beyond end of merged section (4123)
/usr/bin/ld: header.o: access beyond end of merged section (2369)
/usr/bin/ld: header.o: access beyond end of merged section (2086)
/usr/bin/ld: header.o: access beyond end of merged section (3670)
/usr/bin/ld: header.o: access beyond end of merged section (3721)
/usr/bin/ld: header.o: access beyond end of merged section (3181)
/usr/bin/ld: header.o: access beyond end of merged section (4123)
/usr/bin/ld: header.o: access beyond end of merged section (2369)
/usr/bin/ld: header.o: access beyond end of merged section (3678)
/usr/bin/ld: header.o: access beyond end of merged section (3721)
/usr/bin/ld: header.o: access beyond end of merged section (3181)
/usr/bin/ld: header.o: access beyond end of merged section (4123)
/usr/bin/ld: header.o: access beyond end of merged section (2369)
/usr/bin/ld: header.o: access beyond end of merged section (3186)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (2783)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (4581)
/usr/bin/ld: header.o: access beyond end of merged section (4165)
/usr/bin/ld: header.o: access beyond end of merged section (4581)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (2249)
/usr/bin/ld: header.o: access beyond end of merged section (2655)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (4581)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (2169)
/usr/bin/ld: header.o: access beyond end of merged section (4373)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (4434)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (2037)
/usr/bin/ld: header.o: access beyond end of merged section (3785)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (2351)
/usr/bin/ld: header.o: access beyond end of merged section (3333)
/usr/bin/ld: header.o: access beyond end of merged section (3346)
/usr/bin/ld: header.o: access beyond end of merged section (2249)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (4597)
/usr/bin/ld: header.o: access beyond end of merged section (3790)
/usr/bin/ld: header.o: access beyond end of merged section (3785)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (2556)
/usr/bin/ld: header.o: access beyond end of merged section (4448)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (4172)
/usr/bin/ld: header.o: access beyond end of merged section (4084)
/usr/bin/ld: header.o: access beyond end of merged section (3278)
/usr/bin/ld: header.o: access beyond end of merged section (2567)
/usr/bin/ld: /n/eddyfs01/home/jjenny/bin/htslib-1.10.2/libhts.a(header.o)(.debug_info+0x2d0e): reloc against `.debug_loc': error 2
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/popscle] Error 1
make[1]: *** [CMakeFiles/popscle.dir/all] Error 2
make: *** [all] Error 2

**Comment by Gvaihir** [comment]
Your basic linux dependencies are throwing this exception. Try compiling `popscle` on a machine where you have root access and you can install dependencies freely. If that works - work with your admin to install necessary libraries and try other compiler versions.
Also try docker version of demuxlet.

**Comment by jjenny** [comment]
Can you tell me which compiler and version you used to compile the code
successfully?

Thanks,

Jenny

**Comment by Gvaihir** [comment]
```
 ~ >> gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by Gvaihir** [comment]
can the issue be closed?

**Comment by jjenny** [comment]
Yes
