### ISSUE TITLE
Read or UMI based calculations

### ISSUE THREAD

**Issue by jamesnemesh** [statgen/popscle#49]
Hi, this is a question about how the code works, not a bug per-say.

When demuxlet calculates likelihoods, are they done per UMI (somehow collapsing/combining information for each read that sees the same cell+UMI into a base quality) or per read?  The paper references reads, but program has flags for the UMI tag on the read and I noticed you generate random UMIs for ATAC-Seq data, so I wasn't sure.

Thanks for any clarification you can give!

**Comment by hyunminkang** [comment]
--tag-group can be used for cell barcode, and --tag-UMI can be used for UMI. If empty value was specified (e.g. --tag-UMI ""), then it assigns random UMI for each read.

**Comment by jamesnemesh** [comment]
Let's try 2 toy examples:

For a single cell and single UMI sequence I observe 3 reads that overlap a biallelic SNP.  To simplify, assume the base qualities are all the same (30).  

Example One Observed pileup: A,A,A
Example Two Observed pileup: A,A,T

Are the 3 observations treated as independent observations (you calculate likelihoods at the reads level) or are these a single observation (you calculate likelihoods at the UMI level)?

If this is a single observation, how do you take into account disagreements in the pileup?

**Comment by hyunminkang** [comment]
In the current version, the likelihoods are calculated per read level, ignoring UMIs. We believe that it would be ideal to model genotype likelihoods hierarchically accounting for UMIs, but have not implemented it due to increased computational complexity given relatively limited gain of accuracy in our use cases.

**Comment by jamesnemesh** [comment]
Thank you for that very clear explanation!
