### ISSUE TITLE
Error in installation (make: *** [all] Error 2)

### ISSUE THREAD

**Issue by nlawlor** [statgen/popscle#5]
Hello,

I am installing popscle via cmake (version: cmake/3.5.2) with a customized path to the htslib (version 1.2.1):

`cmake --disable-lzma  -DHTS_INCLUDE_DIRS=/mypath/to/htslib/include/  -DHTS_LIBRARIES=/mypath/to/htslib/lib/libhts.a ..`

Which gives me the following messages:

> -- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /projects/stitzel-lab/lawlon/Software/popscle/htslib/include
-- /projects/stitzel-lab/lawlon/Software/popscle/htslib/lib/libhts.a
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.5") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
CMake Warning at CMakeLists.txt:136 (message):
  liblzma library not found, if you specified --disable-lzma when compiling
  libhts, please ignore this warning
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/stitzel-lab/lawlon/Software/popscle/build

Which afterwards, I use the `make` command:

> Scanning dependencies of target popscle
[  2%] Building CXX object CMakeFiles/popscle.dir/allele.cpp.o
[  4%] Building CXX object CMakeFiles/popscle.dir/bam_ordered_reader.cpp.o
[  6%] Building CXX object CMakeFiles/popscle.dir/bcf_chunked_reader.cpp.o
In file included from /projects/stitzel-lab/lawlon/Software/popscle/bcf_chunked_reader.h:35,
                 from /projects/stitzel-lab/lawlon/Software/popscle/bcf_chunked_reader.cpp:24:
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h: In function 'void bcf_format_gt(bcf_fmt_t*, int, kstring_t*)':
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:797: error: 'INT8_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:798: error: 'INT16_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:799: error: 'INT32_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h: In function 'int bcf_enc_inttype(long int)':
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:828: error: 'INT8_MAX' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:828: error: 'INT8_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:829: error: 'INT16_MAX' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:829: error: 'INT16_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h: In function 'void bcf_enc_int1(kstring_t*, int32_t)':
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:835: error: 'INT32_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:837: error: 'INT8_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:840: error: 'INT8_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:841: error: 'INT8_MAX' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:841: error: 'INT8_MIN' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:844: error: 'INT16_MAX' was not declared in this scope
/projects/stitzel-lab/lawlon/Software/popscle/htslib/include/htslib/vcf.h:844: error: 'INT16_MIN' was not declared in this scope
make[2]: *** [CMakeFiles/popscle.dir/bcf_chunked_reader.cpp.o] Error 1
make[1]: *** [CMakeFiles/popscle.dir/all] Error 2
make: *** [all] Error 2

I'm not quite sure what this output means, but it seems like there is an issue with htslib?

Thank you,
Nathan

**Comment by hyunminkang** [comment]
Can you change stdint.h to cstdint in the code and see if it works and let
me know?
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by nlawlor** [comment]
Hi Hyun,

I replaced all instances of "stdint.h" in the code to "cstdint" however, I still receive the exact same error message as before.

**Comment by hyunminkang** [comment]
Can you use different compiler? Not sure what the source was because we
cannot replicate your enviornment

**Comment by nlawlor** [comment]
I tried using a different compiler, (GNU 4.9.2) which seems to get a little further in the installation process:

> -- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /path/to/gcc/4.9.2/bin/cc
-- Check for working C compiler: /path/to/gcc/4.9.2/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /path/to/gcc/4.9.2/bin/c++
-- Check for working CXX compiler: /path/to/gcc/4.9.2/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /opt/compsci/htslib/1.2.1/include
-- /opt/compsci/htslib/1.2.1/lib/libhts.a
-- Found BZip2: /home/lawlon/miniconda3/lib/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/stitzel-lab/lawlon/Software/popscle/build
Scanning dependencies of target popscle
[  2%] Building CXX object CMakeFiles/popscle.dir/allele.cpp.o
[  4%] Building CXX object CMakeFiles/popscle.dir/bam_ordered_reader.cpp.o
[  6%] Building CXX object CMakeFiles/popscle.dir/bcf_chunked_reader.cpp.o
[  9%] Building CXX object CMakeFiles/popscle.dir/bcf_filtered_reader.cpp.o
[ 11%] Building CXX object CMakeFiles/popscle.dir/bh_tsne.cpp.o
[ 13%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_demuxlet.cpp.o
[ 16%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_digital_pileup.cpp.o
[ 18%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_freemuxlet.cpp.o
[ 20%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_gtf_util.cpp.o
[ 23%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_mux_pileup.cpp.o
[ 25%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_simuxlet.cpp.o

But now the error is:

> /projects/stitzel-lab/lawlon/Software/popscle/cmd_cram_simuxlet.cpp: In function 'int32_t cmdCramSimuxlet(int32_t, char**)':
/projects/stitzel-lab/lawlon/Software/popscle/cmd_cram_simuxlet.cpp:139:74: error: 'bam_aux_update_str' was not declared in this scope
    bam_aux_update_str(b, gtag, (int32_t)new_bcd.size()+1, new_bcd.c_str());
                                                                          ^
make[2]: *** [CMakeFiles/popscle.dir/cmd_cram_simuxlet.cpp.o] Error 1

**Comment by hyunminkang** [comment]
This one must be related to htslib. Which version was it used?

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by nlawlor** [comment]
I am using htslib version 1.2.1. Which version do you recommend?

**Comment by nlawlor** [comment]
Switching to htslib version 1.8 did the trick!

Thank you for your help, Hyun!

-Nathan
