### ISSUE TITLE
Question regarding BEST.GUESS column and multiple runs

### ISSUE THREAD

**Issue by bitbioJoel** [statgen/popscle#68]
Hi, I ran Freemuxlet on a time course data set containing 4 different cell lines, I ran it on a bam file per time point. The software does well at separating each time point into the 4 cell lines. I have a question though about whether the BEST.GUESS assignment will be consistent across timepoints? For example will cells assigned to BEST.GUESS 1 in the first time point be the same cell line as BEST.GUESS 1 in the second time point? Or is it possible to pull out which SNPs are associated with the numbers in BEST.GUESS so they can be matched to other timepoints?

**Comment by hyunminkang** [comment]
The cluster assignments will be random. You can match the sample identifies by comparing the genotypes in the output VCFs
