### ISSUE TITLE
Cannot parse posterior probability

### ISSUE THREAD

**Issue by aa9679** [statgen/popscle#76]
Hi, I am using popscle demuxlet using this command:
singularity exec ../code/popscle_2021-05-05-da70fc7.sif popscle demuxlet \
  --plp subset_pileup/subset_samples_to_demuxlet.pileup \
  --vcf lines_used_default_filter_SNP_chr_rename.gvcf \
  --group-list barcodes.tsv \
  --out $DEMUXLET_OUTDIR/demuxlet

But I keep getting this error:
FATAL ERROR - 
[E:int32_t sc_dropseq_lib_t::load_from_plp(const char*, BCFFilteredReader*, const char*, double, double, const char*, bool)] Cannot parse posterior probability at I:31677

terminate called after throwing an instance of 'pException'
  what():  Exception was thrown

Could you please guide. 
Thank you

**Comment by hyunminkang** [comment]
You cannot provide gvcf as input. Please provide VCF sites with multi-sample genotypes consistent to the pileup sites.
