### ISSUE TITLE
install popscle error

### ISSUE THREAD

**Issue by ShuqingL** [statgen/popscle#8]
Hello, when I install this software, I got the error information showed below. 
I can not understand what's meaning. There is any one can help me. waiting.

$ make
Scanning dependencies of target popscle
[  2%] Building CXX object CMakeFiles/popscle.dir/allele.cpp.o
[  4%] Building CXX object CMakeFiles/popscle.dir/bam_ordered_reader.cpp.o
[  7%] Building CXX object CMakeFiles/popscle.dir/bcf_chunked_reader.cpp.o
[  9%] Building CXX object CMakeFiles/popscle.dir/bcf_filtered_reader.cpp.o
[ 11%] Building CXX object CMakeFiles/popscle.dir/bh_tsne.cpp.o
[ 14%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_demuxlet.cpp.o
[ 16%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_digital_pileup.cpp.o
[ 19%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_freemuxlet.cpp.o
[ 21%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_gtf_util.cpp.o
In file included from /usr/include/c++/8/set:60,
                 from /share/Software/popscle/cramore.h:10,
                 from /share/Software/popscle/cmd_cram_gtf_util.cpp:1:
/usr/include/c++/8/bits/stl_tree.h: In instantiation of ‘class std::_Rb_tree<gtfTranscript*, gtfTranscript*, std::_Identity<gtfTranscript*>, gtfComp, std::allocator<gtfTranscript*> >’:
/usr/include/c++/8/bits/stl_set.h:133:17:   required from ‘class std::set<gtfTranscript*, gtfComp>’
/share/Software/popscle/gtf.h:162:36:   required from here
/usr/include/c++/8/bits/stl_tree.h:452:21: error: static assertion failed: comparison object must be invocable with two arguments of key type
       static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/popscle.dir/cmd_cram_gtf_util.cpp.o] Error 1
make[1]: *** [CMakeFiles/popscle.dir/all] Error 2
make: *** [all] Error 2

**Comment by Griffan** [comment]
I assume you are using gcc 8. The problem is caused by a more strict type checking in compiling in gcc 8. I have updated the related code.
Please try to update your repo and compile again, and let us know if it works.
