### ISSUE TITLE
What's the ref_vcf and external_vcf files?

### ISSUE THREAD

**Issue by ShuqingL** [statgen/popscle#9]
Hello,
Actually I don't know what the difference between these two files.
I have data for 8 samples of 10X data processed by cell ranger, and conventional RNASeq data of the same 8 samples.
Do I need to first obtain a VCF file for RNASeq data analysis using, for example, GATK software? But then this is just a VCF file, the two files here can use the same VCF file as input?
I originally thought that this software is to analyze a single sample to detect doublet, but when I see the example of the use of freemuxlet, it is necessary to input the number of samples, is it that I need to analyzed multiple samples together? If multiple samples are analyzed together, how do I combine the 10X data (bam files) for each sample?

I have too many questions. I don't know if anyone can solve my doubts.

**Comment by Griffan** [comment]
The file ref_vcf will provide is the allele frequency which could be obtained from hapmap, 1000g, or dbsnp.
The file external_vcf contains the genotype information of the samples that you multiplexed.

These tools are for multiplexed experiments, if your samples are not sequenced using multiplexing. These tools cannot be used to detect doublet in your case.
